### ISSUE TITLE
Replace doorknob on woodshop door

### ISSUE THREAD

**Issue by john-sanders-2** [TheLab-ms/facilities#17]
Do we have a plan for this yet? Usage of this as a restroom is deterred since the door doesn't lock.

If we have the new knob I'd be happy to install it. I can go pick one up as well.

**Comment by lastcoolnameleft** [comment]
It's been low on the priority list right now.  But as a quick-workaround, could we steal one of the doorknobs from the other doors that we don't use?

**Comment by john-sanders-2** [comment]
I'll try that today or tomorrow. If you need more help and wish to assign any of these facilities requests to me, I'd be happy to help.

**Comment by GeekPatrolMiller** [comment]
I need to replace a doorknob here at the house too. I can run by and get a replacement and bring it down there tonight or Friday.

**Comment by GeekPatrolMiller** [comment]
DoorKnob on Bathroom door in Woodshop has been replaced. We verified that the locking mechanism was on the inside and worked properly. No animals were harmed during this repair. The "broken lock" sign was removed.
