### ISSUE TITLE
workbench

### ISSUE THREAD

**Issue by cloudislands** [TheLab-ms/facilities#18]
Documenting workbench
5ft by 3ft
2x6 construction,  mortise and tenon joinery

[Workbench Shopping List.docx](https://github.com/TheLab-ms/facilities/files/2329245/Workbench.Shopping.List.docx)

<img width="353" alt="bench top glue up" src="https://user-images.githubusercontent.com/40406806/44740434-1191a300-aac0-11e8-9ebf-80e60c74ed7b.png">
<img width="262" alt="benchtop mortise" src="https://user-images.githubusercontent.com/40406806/44740438-15252a00-aac0-11e8-83ea-5d31345fbff0.png">
<img width="256" alt="bench leg" src="https://user-images.githubusercontent.com/40406806/44740444-18b8b100-aac0-11e8-8b8b-8c113ab84c46.png">
<img width="314" alt="workbench" src="https://user-images.githubusercontent.com/40406806/44740447-1a827480-aac0-11e8-87bf-7918c4def31a.png">

**Comment by john-sanders-2** [comment]
Workbench is almost complete. Just some fine tuning on the top to level. Closing issue.
