### ISSUE TITLE
Crash Bar

### ISSUE THREAD

**Issue by lastcoolnameleft** [TheLab-ms/facilities#6]
Tasks:

- [x] Purchase Crash Bar
- [x] Plan Crash Bar Party
- [x] Install Crash Bar

**Comment by thefordness** [comment]
https://www.grainger.com/product/SECURITRON-Push-to-Exit-Bar-45CG45 <-- this appears to be the appropriate product for the door. Special order only, takes a couple of weeks to arrive.

**Comment by GeekPatrolMiller** [comment]
Crash bar has been received!!!

**Comment by lastcoolnameleft** [comment]
We will install the Crashbar at the upcoming "Improve the Space" party on Sunday.  https://www.meetup.com/TheLab-ms/events/251603931/

**Comment by lastcoolnameleft** [comment]
Whoo hoo!  Complete!  Thanks @GeekPatrolMiller @thefordness @Pauldy and Clint!
